---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    alertmanager: main
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"monitoring.coreos.com/v1","kind":"Alertmanager","metadata":{"annotations":{},"labels":{"alertmanager":"main"},"name":"main","namespace":"monitoring"},"spec":{"baseImage":"quay.io/prometheus/alertmanager","dnsConfig":{"nameservers":["10.96.0.10","8.8.8.8"],"options":[{"name":"ndots","value":"2"},{"name":"edns0"}],"searches":["jenkins.svc.cluster.local","svc.cluster.local","cluster.local"]},"dnsPolicy":"None","nodeSelector":{"beta.kubernetes.io/os":"linux"},"replicas":3,"securityContext":{"fsGroup":2000,"runAsNonRoot":true,"runAsUser":1000},"serviceAccountName":"alertmanager-main","version":"v0.17.0"}}'
spec:
  replicas: 3
  selector:
    matchLabels:
      alertmanager: main
      app: alertmanager
  template:
    metadata:
      creationTimestamp:
      labels:
        alertmanager: main
        app: alertmanager
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: alertmanager-main
            defaultMode: 420
        - name: alertmanager-main-db
          emptyDir: {}
      containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:v0.17.0
          args:
            - "--config.file=/etc/alertmanager/config/alertmanager.yaml"
            - "--cluster.listen-address=[$(POD_IP)]:6783"
            - "--storage.path=/alertmanager"
            - "--data.retention=120h"
            - "--web.listen-address=:9093"
            - "--web.route-prefix=/"
            - "--cluster.peer=alertmanager-main-0.alertmanager-operated.monitoring.svc:6783"
            - "--cluster.peer=alertmanager-main-1.alertmanager-operated.monitoring.svc:6783"
            - "--cluster.peer=alertmanager-main-2.alertmanager-operated.monitoring.svc:6783"
          ports:
            - name: web
              containerPort: 9093
              protocol: TCP
            - name: mesh
              containerPort: 6783
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            requests:
              memory: 200Mi
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/alertmanager/config"
            - name: alertmanager-main-db
              mountPath: "/alertmanager"
          livenessProbe:
            httpGet:
              path: "/api/v1/status"
              port: web
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: "/api/v1/status"
              port: web
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: config-reloader
          image: quay.io/coreos/configmap-reload:v0.0.1
          args:
            - "-webhook-url=http://localhost:9093/-/reload"
            - "-volume-dir=/etc/alertmanager/config"
          resources:
            limits:
              cpu: 100m
              memory: 25Mi
          volumeMounts:
            - name: config-volume
              readOnly: true
              mountPath: "/etc/alertmanager/config"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - jenkins.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
          - name: edns0
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: alertmanager-main
      serviceAccount: alertmanager-main
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 2000
      schedulerName: default-scheduler
  serviceName: alertmanager-operated
  updateStrategy:
    type: RollingUpdate
