---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-main
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/alertmanager/metrics'
  labels:
    name: alertmanager
  name: alertmanager-main
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
    - name: web
      protocol: TCP
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-hook-url
  namespace: monitoring
data:
  slack-hook-url: VDZCRkQwTktFL0I2QVZBTktTTC93VFVrQTNwRUJEUmNrR05MT2x3U0hDR0M=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      serviceAccountName: alertmanager-main
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.9.1
          env:
            - name: SLACK_HOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-hook-url
                  key: slack-hook-url
          command: ['/bin/sh', '/etc/alertmanager/configure_secret.sh']
          args:
            - '-config.file=/etc/alertmanager/config.yml'
            - '-storage.path=/alertmanager'
          ports:
            - name: web
              containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager
      nodeSelector:
        beta.kubernetes.io/os: linux
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    receivers:
    - name: email-me
      email_configs:
      - to: bombascter@gmail.com
        from: bombascter@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: bombascter@gmail.com
        auth_identity: bombascter@gmail.com
        auth_password: sgqorxbvnoxwupdg
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: email-me
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: email-me
  configure_secret.sh: |-
    echo 'Configuring Slack hook url.'
    sed -i -e s,API_URL_SECRET,"$SLACK_HOOK_URL",g /etc/alertmanager/config.yml
    exec /bin/alertmanager $*
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      app: alertmanager
