apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6IAogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiJyZWNlaXZlcnMiOiAKLSAibmFtZSI6ICJlbWFpbC1tZSIKICAiZW1haWxfY29uZmlncyI6CiAgLSAidG8iOiAiYm9tYmFzY3RlckBnbWFpbC5jb20iCiAgICAiZnJvbSI6ICJib21iYXNjdGVyQGdtYWlsLmNvbSIKICAgICJzbWFydGhvc3QiOiBzbXRwLmdtYWlsLmNvbTo1ODcKICAgICJhdXRoX3VzZXJuYW1lIjogImJvbWJhc2N0ZXJAZ21haWwuY29tIgogICAgImF1dGhfaWRlbnRpdHkiOiAiYm9tYmFzY3RlckBnbWFpbC5jb20iCiAgICAiYXV0aF9wYXNzd29yZCI6ICJzZ3Fvcnhidm5veHd1cGRnIgoicm91dGUiOiAKICAiZ3JvdXBfYnkiOiAKICAtICJqb2IiCiAgImdyb3VwX2ludGVydmFsIjogIjVtIgogICJncm91cF93YWl0IjogIjMwcyIKICAicmVjZWl2ZXIiOiAiZW1haWwtbWUiCiAgInJlcGVhdF9pbnRlcnZhbCI6ICIxMmgiCiAgInJvdXRlcyI6IAogIC0gIm1hdGNoIjogCiAgICAgICJhbGVydG5hbWUiOiAiV2F0Y2hkb2ciCiAgICAicmVjZWl2ZXIiOiAiZW1haWwtbWUi
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
